# Site settings
name: Wendell Rocha
description: "Fotógrafo amador, leitor assíduo, gamer e desenvolvedor."
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  WendellRocha
facebook_username: wendellrocha
twitter_username: wendellrochaa_
linkedin_username: wendell-rocha-976910148
instagram_username:  wendellrochaa
steam_username: wendros
email: wendellrocha@outlook.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/20341692?s=460&v=4"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
